import { Task } from "../types/Task"

// モックデータの初期値 - 全てのプロジェクトと親タスクは展開状態に設定
export const initialMockTasks: Task[] = [
  {
    id: 1,
    name: "プロジェクトA",
    level: 0,
    isProject: true,
    startDate: "2025-05-10",
    dueDate: "2025-06-30",
    completed: false,
    assignee: "山田太郎",
    notes: "メインプロジェクトのメモ",
    expanded: true, // 必ず展開
    projectId: 1,
    projectName: "プロジェクトA",
    priority: "high",
    tags: ["重要", "開発"],
    color: "#4a6da7",
    order: 1
  },
  {
    id: 2,
    name: "調査フェーズ",
    level: 1,
    isProject: false,
    startDate: "2025-05-10",
    dueDate: "2025-05-20",
    completed: true,
    completionDate: "2025-05-20",
    assignee: "佐藤花子",
    notes: "初期調査完了",
    expanded: true, // 必ず展開
    projectId: 1,
    projectName: "プロジェクトA",
    priority: "medium",
    tags: ["調査"],
    order: 1,
  },
  {
    id: 3,
    name: "市場分析",
    level: 2,
    isProject: false,
    startDate: "2025-05-10",
    dueDate: "2025-05-15",
    completed: true,
    completionDate: "2025-05-15",
    assignee: "佐藤花子",
    notes: "市場分析完了",
    expanded: true, // 展開状態を明示
    projectId: 1,
    projectName: "プロジェクトA",
    priority: "low",
    tags: ["調査", "分析"],
    order: 1,
  },
  {
    id: 4,
    name: "開発フェーズ",
    level: 1,
    isProject: false,
    startDate: "2025-05-21",
    dueDate: "2025-06-15",
    completed: false,
    assignee: "鈴木一郎",
    notes: "開発進行中",
    expanded: true, // 必ず展開
    projectId: 1,
    projectName: "プロジェクトA",
    priority: "high",
    tags: ["開発"],
    order: 2,
  },
  {
    id: 5,
    name: "UIデザイン",
    level: 2,
    isProject: false,
    startDate: "2025-05-21",
    dueDate: "2025-05-30",
    completed: false,
    assignee: "高橋めぐみ",
    notes: "デザインモックアップ進行中",
    expanded: true, // 展開状態を明示
    projectId: 1,
    projectName: "プロジェクトA",
    priority: "medium",
    tags: ["デザイン", "UI"],
    order: 1,
  },
  {
    id: 6,
    name: "プロジェクトB",
    level: 0,
    isProject: true,
    startDate: "2025-06-01",
    dueDate: "2025-07-15",
    completed: false,
    assignee: "山田太郎",
    notes: "サブプロジェクト",
    expanded: true, // 必ず展開
    projectId: 2,
    projectName: "プロジェクトB",
    priority: "medium",
    tags: ["定例"],
    color: "#6a8759",
    order: 2
  },
]