// キーボードショートカット定義
export const KEYBOARD_SHORTCUTS = [
    { key: "Enter", description: "新規タスク追加" },
    { key: "Tab", description: "新規子タスク追加" },
    { key: "Delete", description: "タスク削除" },
    { key: "Ctrl+N", description: "メモを開く" },
    { key: "Ctrl+Shift+C", description: "タスクコピー" },
    { key: "Ctrl+C", description: "クリップボードにコピー" },
    { key: "Ctrl+X", description: "タスク切り取り" },
    { key: "Ctrl+V", description: "クリップボードからペースト" },
    { key: "Ctrl+E", description: "タスク編集" },
    { key: "Space", description: "完了/未完了切替" },
    { key: "+", description: "優先度を上げる" },
    { key: "-", description: "優先度を下げる" },
    { key: "↑", description: "上へ移動" },
    { key: "↓", description: "下へ移動" },
    { key: "←", description: "親へ移動" },
    { key: "→", description: "子へ移動" },
    { key: "Ctrl+Shift+N", description: "新規プロジェクト" },
    { key: "Ctrl+F", description: "検索" },
    { key: "Ctrl+Shift+F", description: "高度な検索" },
    { key: "Ctrl+S", description: "データ保存" },
    { key: "Ctrl+Shift+E", description: "インポート/エクスポート" },
    { key: "F1", description: "ヘルプ" },
    { key: "1", description: "プロジェクトビューに切り替え" },
    { key: "2", description: "タイムラインビューに切り替え" },
    { key: "3", description: "テーブルビューに切り替え" },
    { key: "4", description: "今日のタスクビューに切り替え" },
    { key: "5", description: "かんばんビューに切り替え" }
  ]